import React from 'react'

const Terms = () => {
  return (
    <div className="min-h-screen bg-brand-light">
      <section className="section-shell pt-24 pb-16 flex justify-center">
        <div className="w-full max-w-4xl bg-white shadow-lg rounded-2xl p-10">
          <h1 className="text-3xl font-bold text-brand-dark mb-6 text-center">
            Terms & Conditions – LINK ME
          </h1>

          <p className="text-gray-600 text-center mb-10">
            Please read these terms carefully. By creating an account on LinkMe,
            you agree to all conditions below.
          </p>

          <div className="space-y-6 text-gray-700 leading-7">
            <div>
              <h2 className="text-xl font-semibold mb-2">
                1. Accuracy of Information
              </h2>
              <p>
                You agree to provide accurate, up-to-date, and complete personal
                information including: full legal name, phone number, email
                address, and profile details. Providing misleading or fraudulent
                information may result in account suspension.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-semibold mb-2">
                2. Digital Profile Ownership
              </h2>
              <p>
                Your LinkMe profile is your digital identity. You are fully
                responsible for: the accuracy of your links, uploaded images,
                profile data, and QR/NFC content. LinkMe does not own your data;
                we simply provide the digital platform to manage it.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-semibold mb-2">
                3. NFC & QR Code Usage
              </h2>
              <p>
                When using NFC cards or QR codes generated by LinkMe, you agree
                to:
              </p>
              <ul className="list-disc pl-6 mt-2">
                <li>Use them for personal or business networking only.</li>
                <li>Not embed harmful, malicious, or misleading URLs.</li>
                <li>
                  Not use LinkMe cards to impersonate another person or company.
                </li>
              </ul>
              <p className="mt-2">
                Any misuse of QR/NFC technology will lead to permanent account
                removal.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-semibold mb-2">
                4. Privacy & Data Protection
              </h2>
              <p>
                LinkMe does not sell, rent, or share your personal data with
                third parties. We store your information securely using
                encryption and protected servers. Your public profile may be
                visible to others when shared via QR or NFC.
              </p>
              <p className="mt-2">
                Passwords are encrypted and never stored in plain text.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-semibold mb-2">
                5. User-Generated Content
              </h2>
              <p>You are responsible for the content you add, including:</p>
              <ul className="list-disc pl-6 mt-2">
                <li>Social media links</li>
                <li>Portfolio / business details</li>
                <li>Website URLs</li>
                <li>Images or profile logos</li>
              </ul>
              <p className="mt-2">
                Harmful, offensive, or deceptive content is strictly prohibited.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-semibold mb-2">
                6. Account Security
              </h2>
              <p>
                You are responsible for keeping your password confidential. Any
                activity performed under your account is considered your
                responsibility. LinkMe is not liable for unauthorized access
                caused by weak passwords.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-semibold mb-2">
                7. AI-Generated Recommendations
              </h2>
              <p>
                LinkMe may provide AI-powered design suggestions, profile
                optimization tips, and automated layout recommendations. These
                are optional and based on statistical patterns. You retain full
                control over what appears on your profile.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-semibold mb-2">
                8. Limitation of Liability
              </h2>
              <p>LinkMe is not responsible for:</p>
              <ul className="list-disc pl-6 mt-2">
                <li>Misuse of your shared profile links</li>
                <li>Unauthorized scanning of QR codes</li>
                <li>Incorrect information added by the user</li>
                <li>Third-party services linked from your profile</li>
              </ul>
            </div>

            <div>
              <h2 className="text-xl font-semibold mb-2">
                9. Profile Deletion & Data Removal
              </h2>
              <p>
                You can delete your account at any time. This action permanently
                removes:
              </p>
              <ul className="list-disc pl-6 mt-2">
                <li>All profile data</li>
                <li>All QR/NFC links</li>
                <li>Saved designs</li>
                <li>Uploaded media</li>
              </ul>
              <p className="mt-2">Deleted accounts cannot be recovered.</p>
            </div>

            <div>
              <h2 className="text-xl font-semibold mb-2">
                10. Business & Team Profiles
              </h2>
              <p>
                Business accounts must ensure that all employees listed are real
                and authorized. LinkMe is not responsible for misrepresentation
                by business owners or managers.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-semibold mb-2">
                11. Fair Usage Policy
              </h2>
              <p>You agree not to use LinkMe for:</p>
              <ul className="list-disc pl-6 mt-2">
                <li>Spamming users</li>
                <li>Sending harmful links</li>
                <li>Fraudulent activities</li>
                <li>Identity impersonation</li>
                <li>Illegal business promotion</li>
              </ul>
            </div>

            <div>
              <h2 className="text-xl font-semibold mb-2">12. Acceptance</h2>
              <p>
                By using LinkMe, you confirm that you understand and accept all
                conditions. These terms may be updated at any time; continued
                use means continued agreement.
              </p>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}

export default Terms